import "dotenv/config";
export const ENV = {
  PORT: process.env.PORT,
  MONGO_URI: process.env.MONGO_URI,
  NODE_ENV: process.env.NODE_ENV,
  CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  STREAM_KEY: process.env.STREAM_KEY,
  STREAM_SECRET: process.env.STREAM_SECRET,
  INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
  INNGEST_SIGNINIG_KEY: process.env.INNGEST_SIGNINIG_KEY,
  INNGEST_SIGNINIG_KEY_FALLBACK: process.env.INNGEST_SIGNINIG_KEY_FALLBACK,
};
